import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { RootProvider } from "./rootProvider";
import Darkmode from "./_components/darkmode";
import Logo from "./_components/logo";
import SearchBar from "./_components/searchBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "maple ranking service",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RootProvider>
          <div className="w-full bg-neutral-200 dark:bg-neutral-800 flex justify-center items-center gap-5">
            <Logo />
            <SearchBar />
            <Darkmode />
          </div>
          <div className={inter.className}>{children}</div>
        </RootProvider>
      </body>
    </html>
  );
}
