import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { RootProvider } from "./rootProvider";
import Darkmode from "./_components/darkmode";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "maple ranking service",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RootProvider>
          <div className="w-full bg-red-300 dark:bg-slate-200 flex justify-center gap-5">
            <div>Logo</div>
            <div>Search Bar</div>
            <Darkmode />
          </div>
          <div className={inter.className}>{children}</div>
        </RootProvider>
      </body>
    </html>
  );
}
