import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { RootProvider } from "./rootProvider";
import TopBar from "./_components/topBar";
import Navigation from "./_components/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "maple ranking service",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RootProvider>
          <div className="w-full flex flex-col justify-center items-center bg-neutral-200 dark:bg-neutral-800">
            <TopBar />
            <Navigation />
          </div>
          <div className={inter.className}>{children}</div>
        </RootProvider>
      </body>
    </html>
  );
}
